# Default values for seeker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
updateStrategy: Recreate
pullPolicy: IfNotPresent

# change enabled to false is an external DB should be used
seekerManagedDatabase:
  enabled: true

# fill all fields in order use an external DB
externalDatabaseHost: ""
externalDatabasePort: ""
externalDatabaseName: ""
externalDatabaseUsername: ""
# databasePasswordSecret is the name of the secret that contains the password for the DB
databasePasswordSecret: "seeker-dbpass"

securityContext: {}

storageClassName: ""
persistentVolumeSize: 100Gi

registry: seeker-local
imageTag: 2022.6.0

server:
  image: seeker-server
  xmx: -Xmx4g
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

sensor:
  image: seeker-sensor
  xmx: -Xmx4g
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

postgres:
  image: seeker-postgres
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

nginx:
  image: seeker-nginx
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
