apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seeker.labels" . | nindent 4 }}
    component: nginx
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.updateStrategy }}
  selector:
    matchLabels:
      app: seeker-nginx
  template:
    metadata:
      labels:
        app: seeker-nginx
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      initContainers:
        - name: wait-for-sensor
          image: busybox:stable
          command: ['sh', '-c', 'until nc -vz -w 1 seeker-sensor-service 9911; do echo "Waiting for seeker-sensor service"; sleep 5; done;']
      containers:
        - name: seeker-nginx
          image: {{ .Values.registry }}/{{ .Values.nginx.image }}:{{ .Values.imageTag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 8443
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8}}
---
apiVersion: v1
kind: Service
metadata:
  name: seeker-nginx-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: seeker-nginx
  ports:
    - name: "http"
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.nginx.httpNodePort }}
    - name: "https"
      protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: {{ .Values.nginx.httpsNodePort }}
