apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seeker.labels" . | nindent 4 }}
    component: server
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.updateStrategy }}
  selector:
    matchLabels:
      app: seeker-server
  template:
    metadata:
      labels:
        app: seeker-server
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      initContainers:
        - name: wait-for-database
          image: busybox:stable
          command: ['sh', '-c', 'until nc -vz -w 1 {{ .Values.externalDatabaseHost | default "seeker-postgres-service" | quote }} {{ .Values.externalDatabasePort | default "5432" | quote }}; do echo "Waiting for database service"; sleep 5; done;']
      containers:
        - name: seeker-server
          image: {{ .Values.registry }}/{{ .Values.server.image }}:{{ .Values.imageTag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: SEEKER_SERVER_HTTP_PORT
              value: "8082"
            - name: SEEKER_SERVER_JAVA_OPTS
              value: {{ .Values.server.xmx | quote }}
            - name: SEEKER_BIND_HOST
              value: "0.0.0.0"
            - name: SEEKER_HEALTH_CHECK_MIN_FREE_MEMORY_ENABLED
              value: {{ .Values.server.healthCheckMinFreeMemoryEnabled | quote }}
            - name: SEEKER_HEALTH_CHECK_MIN_FREE_MEMORY
              value: {{ .Values.server.healthCheckMinFreeMemory | quote }}
            - name: SEEKER_HEALTH_CHECK_MIN_FREE_MEMORY_FAILURE_COUNT
              value: {{ .Values.server.healthCheckMinFreeMemoryFailureCount | quote }}
            {{- if .Values.installationType }}
            - name: SEEKER_INSTALLATION_TYPE
              value: {{ .Values.installationType | quote }}
            {{- end }}
            {{- if .Values.smtp.enabled }}
            - name: SEEKER_SMTP_ENABLED
              value: "true"
            - name: SEEKER_SMTP_HOST
              value: {{ .Values.smtp.host | quote }}
            - name: SEEKER_SMTP_PORT
              value: {{ .Values.smtp.port | quote }}
            - name: SEEKER_SMTP_PROTOCOL
              value: {{ .Values.smtp.protocol | quote }}
            - name: SEEKER_SMTP_USERNAME
              value: {{ .Values.smtp.username | quote }}
            - name: SEEKER_SMTP_SENDER
              value: {{ .Values.smtp.sender | quote }}
            - name: SEEKER_SMTP_SUBJECT_PREFIX
              value: {{ .Values.smtp.subjectPrefix | quote }}
            - name: SEEKER_SMTP_TLS
              value: {{ .Values.smtp.tls | quote }}
            {{- end }}
            {{- include "seeker.db.env.vars" . | nindent 12 }}
          ports:
            - containerPort: 8082
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          volumeMounts:
            - name: dbpass
              mountPath: "/opt/seeker/secrets"
              readOnly: true
      volumes:
        - name: dbpass
          secret:
            secretName: {{ .Values.externalDatabasePasswordSecret }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8}}
---
apiVersion: v1
kind: Service
metadata:
  name: seeker-server-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: seeker-server
  ports:
    - name: "http"
      protocol: TCP
      port: 8082
      targetPort: 8082
