# Default values for seeker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
updateStrategy: Recreate
pullPolicy: IfNotPresent

# change enabled to false is an external DB should be used
seekerManagedDatabase:
  enabled: true

# fill all fields in order use an external DB
externalDatabaseHost: ""
externalDatabasePort: ""
externalDatabaseName: ""
externalDatabaseUsername: ""
# externalDatabasePasswordSecret is the name of the secret that contains the password for the DB
externalDatabasePasswordSecret: ""

securityContext: {}

storageClassName: ""
persistentVolumeSize: 100Gi

registry: registry1.dso.mil
imageTag: 2023.1.0

server:
  image: ironbank/synopsys/seeker/seeker-server
  xmx: -Xmx4g
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

sensor:
  image: ironbank/synopsys/seeker/seeker-sensor
  xmx: -Xmx4g
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

postgres:
  image: ironbank/synopsys/seeker/seeker-postgres
  tag: 2022.11.0
  dataFolderName: pg_data_14
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

nginx:
  image: ironbank/synopsys/seeker/seeker-nginx
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
