# Default values for seeker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
updateStrategy: Recreate
pullPolicy: IfNotPresent

# change enabled to false is an external DB should be used
seekerManagedDatabase:
  enabled: true

# fill all fields in order use an external DB
externalDatabaseHost: ""
externalDatabasePort: ""
externalDatabaseName: ""
externalDatabaseUsername: ""
# externalDatabasePasswordSecret is the name of the secret that contains the password for the DB
externalDatabasePasswordSecret: ""

# fill all fields in order use an SMTP server
smtp:
  enabled: false
  host: ""
  port: ""
  protocol: "SMTP"
  username: ""
  sender: "noreply@synopsys.com"
  subjectPrefix: "[Seeker]"
  tls: "true"

# smtpPasswordSecret is the name of the secret that contains the password for the SMTP
smtpPasswordSecret: ""

installationType: ""

securityContext: {}

storageClassName: ""
persistentVolumeSize: 100Gi

registry: registry1.dso.mil
imageTag: 2024.6.0

server:
  image: ironbank/synopsys/seeker/seeker-server
  xmx: -Xmx4g
  healthCheckMinFreeMemoryEnabled: "true"
  healthCheckMinFreeMemory: "500"
  healthCheckMinFreeMemoryFailureCount: "5"
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

sensor:
  image: ironbank/synopsys/seeker/seeker-sensor
  xmx: -Xmx4g
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

postgres:
  image: ironbank/synopsys/seeker/seeker-postgres
  tag: 2024.6.0
  dataFolderName: pg_data_14
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

nginx:
  image: ironbank/synopsys/seeker/seeker-nginx
  httpNodePort: 30080
  httpsNodePort: 30443
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
